# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk.xci
# IP: The module: 'vga_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk.xci
# IP: The module: 'vga_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
