# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/code/code.xci
# IP: The module: 'code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/code/code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'code'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/code/code.xci
# IP: The module: 'code' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/code/code_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'code'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
