# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.cache/wt [current_project]
set_property parent.project_path C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Max/Desktop/RISC_V_PIPE/bram/pic_coe/0.coe
add_files C:/Users/Max/Desktop/RISC_V_PIPE/bram/pic_coe/1.coe
add_files C:/Users/Max/Desktop/RISC_V_PIPE/bram/c_code/sum.coe
read_verilog -library xil_defaultlib {
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/define.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/ctrl.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/div.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/ex.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/ex_mem.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/ex_stage.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/forward_unit.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/id.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/id_ex.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/mem.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/mem_stage.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/mem_wb.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/mux3_1.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/pc.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/pc_id.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/vga/vga_define.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/vga/pic_drive.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/ram.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/regs.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/risc_v_pipe_top.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/risc_v_soc.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/rom.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/vga/vga_control.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/vga/vga_drive.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/vga/vga_top.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/rtl/wb.v
  C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/imports/srcs/top/top_module.v
}
read_ip -quiet C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/zero_cell/zero_cell.xci
set_property used_in_implementation false [get_files -all c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/zero_cell/zero_cell_ooc.xdc]

read_ip -quiet C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/one_cell/one_cell.xci
set_property used_in_implementation false [get_files -all c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/one_cell/one_cell_ooc.xdc]

read_ip -quiet C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/code/code.xci
set_property used_in_implementation false [get_files -all c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/code/code_ooc.xdc]

read_ip -quiet C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk.xci
set_property used_in_implementation false [get_files -all c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/sources_1/ip/vga_clk/vga_clk_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/constrs_1/imports/cnstr/cnstr.xdc
set_property used_in_implementation false [get_files C:/Users/Max/Desktop/RISC_V_PIPE/project/RISC_V_PIPE/RISC_V_PIPE.srcs/constrs_1/imports/cnstr/cnstr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
